# Generated by Django 3.0.4 on 2020-03-14 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200, verbose_name='Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='Enq_No',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq_no', models.CharField(max_length=20, verbose_name='Enq_No')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Name_of_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=100, verbose_name='Project_Name')),
                ('enq_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Enq_No')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Enq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectEnq', models.CharField(max_length=100, verbose_name='Project_Enq')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Starting Time')),
                ('end_time', models.TimeField(verbose_name='Ending Time')),
                ('submit_data', models.DateField(verbose_name='Submit Date')),
                ('hours', models.DurationField(blank=True, null=True, verbose_name='Hours')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Activity')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Department')),
                ('enq_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Enq_No')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Location')),
                ('name_of_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Name_of_Project')),
                ('projectEnq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Project_Enq')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employeeid')),
            ],
        ),
        migrations.AddField(
            model_name='name_of_project',
            name='projectEnq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Project_Enq'),
        ),
        migrations.AddField(
            model_name='enq_no',
            name='projectEnq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Project_Enq'),
        ),
        migrations.AddField(
            model_name='activity',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_app.Department'),
        ),
    ]
